[package]
name = "hello_world"
version = "0.1.0"
authors = ["David Raifaizen <d-raif@hotmail.com>"]

[dependencies]
schema = { path = "../schema" }
schema_derive = { path = "../schema_derive" }
serde = "*"
serde_derive = "*"
